// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCngw6nRM0bRaImcklkJLoX9XdNN4SQ0aQ',
    appId: '1:181854216134:web:7e0b9304e1ac923621dcc7',
    messagingSenderId: '181854216134',
    projectId: 'fitnessfinal-248a1',
    authDomain: 'fitnessfinal-248a1.firebaseapp.com',
    storageBucket: 'fitnessfinal-248a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFnrUUN8IL6yAYwf2QZ2xCQ-V29O6qFHo',
    appId: '1:181854216134:android:c7e39f2d5902473521dcc7',
    messagingSenderId: '181854216134',
    projectId: 'fitnessfinal-248a1',
    storageBucket: 'fitnessfinal-248a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_LqDBwTlkBlheR_-kh4A7pgba0Ftw4LI',
    appId: '1:181854216134:ios:a9a99bb0f5dc830021dcc7',
    messagingSenderId: '181854216134',
    projectId: 'fitnessfinal-248a1',
    storageBucket: 'fitnessfinal-248a1.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_LqDBwTlkBlheR_-kh4A7pgba0Ftw4LI',
    appId: '1:181854216134:ios:a9a99bb0f5dc830021dcc7',
    messagingSenderId: '181854216134',
    projectId: 'fitnessfinal-248a1',
    storageBucket: 'fitnessfinal-248a1.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCngw6nRM0bRaImcklkJLoX9XdNN4SQ0aQ',
    appId: '1:181854216134:web:a2752f06e689f08321dcc7',
    messagingSenderId: '181854216134',
    projectId: 'fitnessfinal-248a1',
    authDomain: 'fitnessfinal-248a1.firebaseapp.com',
    storageBucket: 'fitnessfinal-248a1.firebasestorage.app',
  );
}
